rm(list=ls())
setwd("/Users/Raga/Dropbox/Documents/RNA splicing/")
isoforms <- read.table("DEseq2-results.txt", sep="\t", header=TRUE)
genes <- read.table("DEseq2-results-exons.txt", sep="\t", header=TRUE)
sig_iso=na.omit(isoforms[isoforms$padj<0.05,])
sig_gene_temp=na.omit(genes[genes$padj<0.05,])
geneann=data.frame(isoforms[,9])
geneann2=data.frame(isoforms[,13])
geneanno=cbind(geneann,geneann2)
colnames(geneanno)=c("gene.musg","geneID")
sig_gene=merge(sig_gene_temp,geneanno,all.x=FALSE)
